image: gitlab.cosmian.com:5000/core/ci-java-8:latest

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo/
  SCCACHE_DIR: ${CI_PROJECT_DIR}/.cache/sccache
  COSMIAN_SERVER_URL: http://localhost:9998
  KMS_PUBLIC_PATH: /tmp
  KMS_PRIVATE_PATH: /tmp
  KMS_SHARED_PATH: /tmp

stages:
  - build
  - publish

build:
  stage: build
  services:
    - name: gitlab.cosmian.com:5000/core/kms:2.2.0_ci
      alias: kms_ci
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 3 mos

publish:
  stage: publish
  before_script:
    - yum -y install gnupg2
    - mkdir -p ~/.m2 ~/.gpg
    - echo "$M2_SETTINGS" > ~/.m2/settings.xml
    - echo "$MAVEN_GPG_PRIVATE_KEY" > ~/.gpg/maven_gpg_private_key.asc
    - gpg --import ~/.gpg/maven_gpg_private_key.asc
  script:
    - mvn clean deploy -Dmaven.test.skip
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/'
