version: "3.4"
services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kms
      - POSTGRES_DB=kms
      - POSTGRES_PASSWORD=kms
      - PGDATA=/tmp/postgres2
  kms:
    container_name: kms
    image: gitlab.cosmian.com:5000/core/kms:2.3.1_ci
    environment:
      - KMS_HOSTNAME=0.0.0.0
      - KMS_PUBLIC_PATH=/tmp
      - KMS_PRIVATE_PATH=/tmp
      - KMS_SHARED_PATH=/tmp
    ports:
      - "9998:9998"
    depends_on:
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
