---
version: '3.4'
services:
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kms
      - POSTGRES_DB=kms
      - POSTGRES_PASSWORD=kms
      - PGDATA=/tmp/postgres2
  kms:
    container_name: kms
    image: ghcr.io/cosmian/kms:4.11.3
    ports:
      - 9998:9998
    depends_on:
      - db

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  findex_cloud:
    image: ghcr.io/cosmian/findex_cloud:0.3.1
    ports:
      - 8080:8080
